## CIR model 

The $Q$ dynamics of the short rate in the C.I.R. model is the following:

$$
    dr_t = k(\theta - r_t)dt +\sigma\sqrt{r_t}dW_t
$$

The conditional mean and variance are:

$$
\mathbb{E}[r_t|r_s] = r_s e^{-k(t-s)} + \theta(1-e^{-k(t-s)}) \quad \forall s<t 
$$

$$
\operatorname{Var}[r_t \mid r_s] = r_s \frac{\sigma^2}{k} \left(e^{-k(t-s)} - e^{-2k(t-s)} \right) + \frac{\theta \sigma^2}{2k} (1 - e^{-k(t-s)})^2 \quad \forall s < t
$$

The zero-coupon bond pricing formula:
$$
    \begin{split}
        &P(t,T) = \exp\{A(t,T) - B(t,T)r_t\}\\
        &B(t,T) = \frac{2(\exp((T-t)h)-1)}{2h + (k+h)(\exp\{(T-t)h\}-1)}\\
        &A(t,T) = \frac{2k\theta}{\sigma^2}\log\bigg\{\frac{2h\exp\{(k+h)(T-t)/2\}}{2h + (k+h)(\exp\{(T-t)h\}-1)}\bigg\}\\
        &h = \sqrt{k^2 + 2\sigma^2}
    \end{split}
$$

In [9]:
import numpy as np 
from functions import *
from scipy.optimize import minimize, Bounds
import matplotlib.pyplot as plt

In [2]:
true_theta = .025
true_k = 22.524
true_sigma = .952
true_r0 = .00175

maturities = np.cumsum(np.ones(36) * (1/12))
True_bonds = CIR_bond(true_r0, true_theta, true_k, true_sigma, maturities)

In [3]:
maturities

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333,
       0.91666667, 1.        , 1.08333333, 1.16666667, 1.25      ,
       1.33333333, 1.41666667, 1.5       , 1.58333333, 1.66666667,
       1.75      , 1.83333333, 1.91666667, 2.        , 2.08333333,
       2.16666667, 2.25      , 2.33333333, 2.41666667, 2.5       ,
       2.58333333, 2.66666667, 2.75      , 2.83333333, 2.91666667,
       3.        ])

In [4]:
True_bonds

array([0.99879194, 0.99684789, 0.99479534, 0.99272992, 0.9906662 ,
       0.98860637, 0.98655076, 0.98449941, 0.98245233, 0.98040951,
       0.97837093, 0.9763366 , 0.97430649, 0.9722806 , 0.97025893,
       0.96824146, 0.96622818, 0.96421909, 0.96221418, 0.96021344,
       0.95821686, 0.95622443, 0.95423614, 0.95225198, 0.95027196,
       0.94829605, 0.94632424, 0.94435654, 0.94239293, 0.9404334 ,
       0.93847795, 0.93652656, 0.93457923, 0.93263595, 0.93069671,
       0.9287615 ])

In [5]:
parms = np.array([0.015,  19, 0.6, .00175])
res = calibrate_cir(parms, True_bonds, maturities, method='L-BFGS-B')

In [6]:
res.x

array([2.50361067e-02, 1.90000022e+01, 5.99999832e-01, 4.46016391e-03])

In [7]:
res.fun

1.1147996316367324e-07

In [8]:
res.jac

array([-5.26159661e-10, -7.47817534e-08, -4.94489759e-09, -2.07444986e-10])