## The Vasicek model

The $Q$ dynamics of the short rate in the C.I.R. model is the following:

$$
    dr_t = k(\theta - r_t)dt +\sigma dW_t
$$

The conditional mean and variance are:

$$
\mathbb{E}[r_t|r_s] = r_s e^{-k(t-s)} + \theta(1-e^{-k(t-s)}) \quad \forall s<t 
$$

$$
\operatorname{Var}[r_t \mid r_s] = \frac{\sigma^2}{2k} (1 - e^{-2k(t-s)}) \quad \forall s < t
$$

The zero-coupon bond pricing formula
$$
\begin{split}
    &P(t,T) = \exp\{A(t,T) - B(t,T)r_t\}\\
    &A(t,T) = \bigg(\theta -\frac{\sigma^2}{2k^2}\bigg)\bigg(B(t,T) - (T-t)\bigg) - \frac{\sigma^2}{4k}B(t,T)^2\\
    &B(t,T) = \frac{1}{k}\bigg(1 - \exp(-k(T-t))\bigg)
\end{split}
$$

In [1]:
import numpy as np 
from functions import *
from scipy.optimize import minimize, Bounds
import matplotlib.pyplot as plt

In [2]:
true_theta = .025
true_k = 22.212
true_sigma = .952
r0 = .00175
maturities = np.cumsum(np.ones(12) * (1/12))
 
True_bonds = Vasicek_bond(r0, true_theta, true_k, true_sigma, maturities)

In [3]:
True_bonds

array([0.99882666, 0.99695197, 0.99497326, 0.99298169, 0.99099147,
       0.98900482, 0.9870221 , 0.98504334, 0.98306854, 0.9810977 ,
       0.97913082, 0.97716787])

In [4]:
maturities

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333,
       0.91666667, 1.        ])

In [5]:
parms = np.array([ .01, 15, .5]) 

res = calibrate_vasicek(parms, True_bonds, maturities, r0, 'L-BFGS-B')

In [6]:
res.x

array([ 0.02589805, 15.00000243,  0.49996799])

In [7]:
res.fun

9.492793841131658e-06